# Generated by Django 3.2.8 on 2023-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='ФИО ученика')),
                ('student_date', models.DateField(verbose_name='Дата рождния ученика')),
                ('family_name', models.CharField(max_length=150, verbose_name='ФИО родителя/законного представителя')),
                ('contact_phone_number', models.IntegerField(verbose_name='Контактный номер телефона')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес проживания')),
            ],
        ),
    ]
